#!/bin/bash

DETAIL_PATH=detail
UTIL_PATH=utils
INTERFACE_FILE=interface.hh
HANDLE_FILE=handle_for_interface.hh
DETAIL_FILE=detail_for_interface.hh
GIVEN_INTERFACE=plain_interface.hh
CLANG_PATH=$1

function generate_test_folder {
  rm -rf $1
  mkdir $1
  mkdir $1/$DETAIL_PATH
  cp ../$1/* $1/
 }

function prepare_test_case {
    generate_test_folder $1
    python2 ../generate_tests.py --namespace-name $2 --class-name "Fooable" --test-file $1/interface_test.cpp --form ../interface_test.form $3
    ../generate_given_interface $2 $GIVEN_INTERFACE
}

# remove previously generate files
rm -rf gen/ && mkdir gen
cp ../util.hh gen/
cp ../mock_fooable.hh gen/
cd gen
mkdir $UTIL_PATH

DIR=pimpl_basic_header_only
echo "Generate test case"
prepare_test_case $DIR PimplBasicHeaderOnly
#--clang-path $CLANG_PATH
python2 ../../../pimpl.py --interface-header-file $DIR/$INTERFACE_FILE --interface-source-file $DIR/interface.cpp  Fooable $GIVEN_INTERFACE

cd ..

# run unit tests
rm -rf build && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug && make && ./unit_tests && cd ..
