language: cpp
before_install:
  - $CXX --version
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-5
  - sudo apt-get remove fenics
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-add-repository "deb http://llvm.org/apt/trusty llvm-toolchain-trusty-3.8 main" -y
  # - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted" -y
  - sudo apt-get update -qq
  # - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  # - tar xf lcov_1.11.orig.tar.gz
  # - sudo make -C lcov-1.11/ install
  # install lcov to coveralls conversion + upload tool
  # - gem install coveralls-lcov
  - sudo apt-get install libclang-3.8-dev -qq
  - sudo apt-get install build-essential checkinstall -qq
  - sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev -qq
  - sudo apt-get install python-pip -qq
  - sudo pip install clang
  - sudo apt-get install libgtest-dev -qq
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make 
  # copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
  - sudo cp *.a /usr/lib
  - cd $TRAVIS_BUILD_DIR
script:
  - cd tests
  - ./run
  - cd build && rm -rf * && cmake .. -DCMAKE_BUILD_TYPE=Release && make && ./unit_tests && cd ..
  - cd ..
after_success:
  # - cd build
  # - ctest
  # - lcov --capture --no-external --directory . --base-directory ../fung --output-file coverage.info
  # - sed  's@/home/travis/build/lubkoll/FunG/@/@g' coverage.info
  # - coveralls-lcov --repo-token fPyYknPYYq6DiXlBDUOXzHGq8RUI6o8QO coverage.info
