language: c++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - llvm-toolchain-precise-3.7
    - llvm-toolchain-precise-3.8
    packages:
    - g++-5
    - gcc-5
    - g++-6
    - gcc-6
    - clang-3.6
    - libclang-3.6-dev
    - clang-3.7
    - libclang-3.7-dev
    - clang-3.8
    - libclang-3.8-dev
    - libgtest-dev
    - build-essential
    - checkinstall
    - libreadline-gplv2-dev 
    - libncursesw5-dev 
    - libssl-dev 
    - libsqlite3-dev 
    - tk-dev 
    - libgdbm-dev 
    - libc6-dev 
    - libbz2-dev
    - python-pip
    - clang-format-3.8

env:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.6.2
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.7.1
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    # Linux
    # GCC 5
    - os: linux
      env: COMPILER=g++-5 CCOMPILER=gcc-5
      compiler: gcc

    # GCC 6
    - os: linux
      env: COMPILER=g++-6 CCOMPILER=gcc-6
      compiler: gcc
      
    # Clang 3.6
    - os: linux
      env: COMPILER=clang++-3.6 CCOMPILER=clang-3.6
      compiler: clang
      
    # Clang 3.7
    - os: linux
      env: COMPILER=clang++-3.7 CCOMPILER=clang-3.7
      compiler: clang
      
    # Clang 3.8
    - os: linux
      env: COMPILER=clang++-3.8 CCOMPILER=clang-3.8
      compiler: clang
      
    # OSX
    # Xcode 6.4
    - os: osx
      osx_image: xcode6.4
      
    # Xcode 7.3
    - os: osx
      osx_image: xcode7.3
      
    # Xcode 8
    - os: osx
      osx_image: xcode8
      
install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  
  ############################################################################
  # Setup default versions and override compiler if needed
  ############################################################################
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; export CC=${CCOMPILER}; fi
  
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      brew install python
    fi
  - sudo pip install clang
  - git clone https://github.com/google/googletest.git
  - cd googletest && mkdir build && cd build && cmake .. && make
  - sudo cp -r ../googletest/include/gtest /usr/local/include/
  - sudo cp googlemock/gtest/lib*.a /usr/local/lib
script:
  - cd $TRAVIS_BUILD_DIR
  - cd tests
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      -/run /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
    else
      ./run /usr/lib/llvm-3.8/lib
    fi
#  - rm -rf build && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make && ./unit_tests
