#!/bin/bash

HANDLE_FOLDER=handles
INTERFACE_FILE=interface.hh
GIVEN_INTERFACE=plain_interface.hh

INTERFACE_FILE_CPP=${INTERFACE_FILE:0:`expr index "$INTERFACE_FILE" .hh`-1}.cpp

echo $CWD

function prepare_test_case {
  rm -rf $1 && mkdir $1
  cp ../$1/* $1/
  cd $1
  ../../generate_given_interface $2 $GIVEN_INTERFACE
  ./generate_interface $HANDLE_FOLDER $INTERFACE_FILE $INTERFACE_FILE_CPP $GIVEN_INTERFACE
  cd ..
}

# remove previously generate files
rm -rf gen/ && mkdir gen
cp util.hh gen/
cp mock_fooable.hh gen/
cd gen

# inheritance-based type-erased interfaces
prepare_test_case basic Basic
prepare_test_case basic_header_only BasicHeaderOnly

prepare_test_case cow COW
prepare_test_case cow_header_only COWHeaderOnly

prepare_test_case sbo SBO
prepare_test_case sbo_header_only SBOHeaderOnly

prepare_test_case sbo_cow SBO_COW
prepare_test_case sbo_cow_header_only SBO_COWHeaderOnly

# vtable-based type-erased interfaces
prepare_test_case vtable_basic VTableBasic
prepare_test_case vtable_basic_header_only VTableBasicHeaderOnly

prepare_test_case vtable_cow VTableCOW
prepare_test_case vtable_cow_header_only VTableCOWHeaderOnly

cd ..

# run unit tests
rm -rf build && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug && make && ./unit_tests && cd ..
