#!/bin/bash

HANDLE_FOLDER=handles
INTERFACE_FILE=interface.hh
GIVEN_INTERFACE=plain_interface.hh

echo $CWD

function prepare_test_case {
  rm -rf $1 && mkdir $1
  cp ../$1/* $1/
  python2 ../generate_tests.py --namespace-name $2 --class-name "Fooable" --test-file $1/interface_test.cpp --form ../interface_test.form $3
  cd $1
  mkdir $HANDLE_FOLDER
  ../../generate_given_interface $2 $GIVEN_INTERFACE
  ./generate_interface $HANDLE_FOLDER $INTERFACE_FILE $GIVEN_INTERFACE
  cd ..
}

function prepare_vtable_test_case {
  rm -rf $1 && mkdir $1
  cp ../$1/* $1/
  python2 ../generate_tests.py --namespace-name $2 --class-name "Fooable" --test-file $1/interface_test.cpp --form ../vtable_interface_test.form $3
  cd $1
  mkdir $HANDLE_FOLDER
  ../../generate_given_interface $2 $GIVEN_INTERFACE
  ./generate_interface $HANDLE_FOLDER $INTERFACE_FILE $GIVEN_INTERFACE
  cd ..
}

# remove previously generate files
rm -rf gen/ && mkdir gen
cp util.hh gen/
cp mock_fooable.hh gen/
cd gen

# inheritance-based type-erased interfaces
prepare_test_case basic Basic
prepare_test_case basic_header_only BasicHeaderOnly

prepare_test_case cow COW
prepare_test_case cow_header_only COWHeaderOnly

prepare_test_case sbo SBO --sbo
prepare_test_case sbo_header_only SBOHeaderOnly --sbo

prepare_test_case sbo_cow SBO_COW --sbo
prepare_test_case sbo_cow_header_only SBO_COWHeaderOnly --sbo

# vtable-based type-erased interfaces
prepare_vtable_test_case vtable_basic VTableBasic
prepare_vtable_test_case vtable_basic_header_only VTableBasicHeaderOnly

prepare_vtable_test_case vtable_cow VTableCOW
prepare_vtable_test_case vtable_cow_header_only VTableCOWHeaderOnly

prepare_vtable_test_case vtable_sbo VTableSBO --sbo
prepare_vtable_test_case vtable_sbo_header_only VTableSBOHeaderOnly --sbo

prepare_vtable_test_case vtable_sbo_cow VTableSBOCOW --sbo
prepare_vtable_test_case vtable_sbo_cow_header_only VTableSBOCOWHeaderOnly --sbo

cd ..

# run unit tests
rm -rf build && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug && make && ./unit_tests && cd ..
