#!/bin/bash

HANDLE_FOLDER=$1
INTERFACE_FILE=$2
GIVEN_INTERFACE=$3

python2 ../../../type_erase.py --header-only -cow -sbo --handle-folder $HANDLE_FOLDER --handle-file handles/handle_for_$INTERFACE_FILE --interface-file $INTERFACE_FILE $GIVEN_INTERFACE

